services:
  madara-devnet:
    image: ghcr.io/madara-alliance/madara:latest
    restart: unless-stopped
    command: "--name madara --base-path ../madara_db --network main --full --telemetry-disabled --rpc-port 9944 --rpc-cors '*' --rpc-external --no-l1-sync --rpc-methods unsafe"

  explorer:
    image: sotazklabs/stark_compass_explorer:v0.2.38
    build:
      context: .
    ports:
      - "4001:4001"
    environment:
      - DB_TYPE=postgresql # set to postgresql if you want to use postgresql, empty otherwise (sqlite).
      - DISABLE_MAINNET_SYNC=true # Set to true if you want to disable mainnet sync
      - DISABLE_SEPOLIA_SYNC=false # Set to true if you want to disable sepolia sync
      - RPC_API_HOST=http://madara-devnet:9944 # Set to your sepolia rpc api host, is will be used in the explorer as "Sepolia"
      - SEPOLIA_RPC_API_HOST=http://madara-devnet:9944 # Set to your sepolia rpc api host, is will be used in the explorer as "Sepolia"
      - SECRET_KEY_BASE=JyULoT5cLBifW+XNEuCTVoAb+SaFgQt9j227RN0cKpR3wTsrApGd1HNcgeopemyl
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - PHX_HOST=10.20.10.121
      - PORT=4001

  postgres:
    image: postgres:14.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
